// <auto-generated />
using GenerationsPOS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenerationsPOS.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231109215836_AddLogo")]
    partial class AddLogo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("GenerationsPOS.PointOfSale.Data.CompanySettings", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("COMPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardPaymentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CashPaymentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckPaymentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsignorCreditPaymentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultCustomerJobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Footer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserTheme")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Configuration");
                });
#pragma warning restore 612, 618
        }
    }
}
